data_specs:
  dataset_name: amass_rec
  file_path: /hdd/zen/data/ActBound/AMASS/amass_take7.pkl
  flip_cnd: 0
  has_smpl_root: true
  traj_dim: 144
  t_total: 90
  nc: 2
  load_class: -1
  root_dim: 6
  flip_time: true

loss_specs:
  loss_names:
    - MSE
    - MSE_RT
    - KLD
  loss_weights:
    mse: 1
    kld: 0.1
    mse_rt: 20

model_specs:
  nz: 512
  model_name: VAErecV2
  rnn_type: gru
  x_birnn: true
  e_birnn: true
  use_drnn_mlp: false
  nx_rnn: 512
  nh_mlp: 
    - 1024
    - 512
norm_data: false

lr: 1.e-4

batch_size: 512
num_epoch_fix: 500
num_samples: 500000
num_epoch: 1000
save_model_interval: 10


vis_model: human36m_vis_sample_single_v1